import { CMSPageSchema, BlogPageData } from '../types';

export const blogSchema: CMSPageSchema = {
    pageId: 'blog',
    pageName: 'Growth Blog - Listing Page',
    sections: [
        {
            id: 'pageHeader',
            title: 'Page Header',
            icon: 'document',
            fields: [
                { name: 'mainHeading', type: 'text', label: 'Main Heading', placeholder: 'Insights for Your Growth' },
                { name: 'subHeading', type: 'text', label: 'Subtitle', placeholder: 'Our perfect plan from our deep expertise in tech for your personal growth' },
            ],
        },
        {
            id: 'blog1',
            title: 'Blog Post 1: SEO 2025',
            icon: 'tag',
            fields: [
                { name: 'category', type: 'text', label: 'Category Tag', placeholder: 'STRATEGY' },
                { name: 'title', type: 'text', label: 'Blog Title', placeholder: 'The Death of Traditional SEO: What\'s Next in 2025?' },
                { name: 'excerpt', type: 'html', label: 'Excerpt/Description', placeholder: 'Search engines are changing. AI overviews are taking over...' },
                { name: 'author', type: 'text', label: 'Author Name', placeholder: 'Gunn Malhotra' },
                { name: 'date', type: 'text', label: 'Publish Date', placeholder: 'Oct 24, 2024' },
                { name: 'readTime', type: 'text', label: 'Read Time', placeholder: '6 min read' },
                { name: 'image', type: 'image', label: 'Featured Image', specs: 'MAX 2MB • PNG, JPG, WEBP' },
                { name: 'slug', type: 'text', label: 'URL Slug', placeholder: 'seo-2025' },
            ],
        },
        {
            id: 'blog2',
            title: 'Blog Post 2: UX/UI Design',
            icon: 'tag',
            fields: [
                { name: 'category', type: 'text', label: 'Category Tag', placeholder: 'UX/UI DESIGN' },
                { name: 'title', type: 'text', label: 'Blog Title', placeholder: 'Why Your Website Conversion Rate is Low (And How to Fix It)' },
                { name: 'excerpt', type: 'html', label: 'Excerpt/Description', placeholder: 'It\'s not your traffic, it\'s your funnel. We break down the 5 most common UX mistakes...' },
                { name: 'author', type: 'text', label: 'Author Name', placeholder: 'Sarah Jenkins' },
                { name: 'date', type: 'text', label: 'Publish Date', placeholder: 'Oct 20, 2024' },
                { name: 'readTime', type: 'text', label: 'Read Time', placeholder: '8 min read' },
                { name: 'image', type: 'image', label: 'Featured Image', specs: 'MAX 2MB • PNG, JPG, WEBP' },
                { name: 'slug', type: 'text', label: 'URL Slug', placeholder: 'conversion-rate-optimization' },
            ],
        },
        {
            id: 'blog3',
            title: 'Blog Post 3: Paid Media',
            icon: 'tag',
            fields: [
                { name: 'category', type: 'text', label: 'Category Tag', placeholder: 'PAID MEDIA' },
                { name: 'title', type: 'text', label: 'Blog Title', placeholder: 'Maximizing ROAS on Meta Ads in a Post-Cookie World' },
                { name: 'excerpt', type: 'html', label: 'Excerpt/Description', placeholder: 'Targeting has become harder. Here are the first-party data strategies...' },
                { name: 'author', type: 'text', label: 'Author Name', placeholder: 'Mike Ross' },
                { name: 'date', type: 'text', label: 'Publish Date', placeholder: 'Oct 15, 2024' },
                { name: 'readTime', type: 'text', label: 'Read Time', placeholder: '5 min read' },
                { name: 'image', type: 'image', label: 'Featured Image', specs: 'MAX 2MB • PNG, JPG, WEBP' },
                { name: 'slug', type: 'text', label: 'URL Slug', placeholder: 'roas-meta-ads' },
            ],
        },
        {
            id: 'blog4',
            title: 'Blog Post 4: Branding',
            icon: 'tag',
            fields: [
                { name: 'category', type: 'text', label: 'Category Tag', placeholder: 'BRANDING' },
                { name: 'title', type: 'text', label: 'Blog Title', placeholder: 'Brand Storytelling: The Only Moat Left' },
                { name: 'excerpt', type: 'html', label: 'Excerpt/Description', placeholder: 'In an age of AI content, human connection is premium...' },
                { name: 'author', type: 'text', label: 'Author Name', placeholder: 'Gunn Malhotra' },
                { name: 'date', type: 'text', label: 'Publish Date', placeholder: 'Oct 10, 2024' },
                { name: 'readTime', type: 'text', label: 'Read Time', placeholder: '7 min read' },
                { name: 'image', type: 'image', label: 'Featured Image', specs: 'MAX 2MB • PNG, JPG, WEBP' },
                { name: 'slug', type: 'text', label: 'URL Slug', placeholder: 'brand-storytelling' },
            ],
        },
    ],
};

export const defaultBlogData: BlogPageData = {
    pageHeader: {
        mainHeading: 'Insights for Your Growth',
        subHeading: 'Our perfect plan from our deep expertise in tech for your personal growth',
    },
    blog1: {
        category: 'STRATEGY',
        title: "The Death of Traditional SEO: What's Next in 2025?",
        excerpt: 'Search engines are changing. AI overviews are taking over. Here is how your brand can survive the shift.',
        author: 'Gunn Malhotra',
        date: 'Oct 24, 2024',
        readTime: '6 min read',
        image: 'https://images.unsplash.com/photo-1571786256017-aee7a0c009b6?auto=format&fit=crop&q=80&w=1200',
        slug: 'seo-2025',
    },
    blog2: {
        category: 'UX/UI DESIGN',
        title: 'Why Your Website Conversion Rate is Low (And How to Fix It)',
        excerpt: "It's not your traffic, it's your funnel. We break down the 5 most common UX mistakes killing your sales.",
        author: 'Sarah Jenkins',
        date: 'Oct 20, 2024',
        readTime: '8 min read',
        image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=1200',
        slug: 'conversion-rate-optimization',
    },
    blog3: {
        category: 'PAID MEDIA',
        title: 'Maximizing ROAS on Meta Ads in a Post-Cookie World',
        excerpt: 'Targeting has become harder. Here are the first-party data strategies we use to get 4x returns for clients.',
        author: 'Mike Ross',
        date: 'Oct 15, 2024',
        readTime: '5 min read',
        image: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?auto=format&fit=crop&q=80&w=1200',
        slug: 'roas-meta-ads',
    },
    blog4: {
        category: 'BRANDING',
        title: 'Brand Storytelling: The Only Moat Left',
        excerpt: 'In an age of AI content, human connection is premium. Learn how to craft a narrative that resonates.',
        author: 'Gunn Malhotra',
        date: 'Oct 10, 2024',
        readTime: '7 min read',
        image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&q=80&w=1200',
        slug: 'brand-storytelling',
    },
};

