import { CMSPageSchema, HomePageData } from '../types';

export const homeSchema: CMSPageSchema = {
    pageId: 'home',
    pageName: 'Landing Page',
    sections: [
        {
            id: 'hero',
            title: 'Hero Module',
            icon: 'document',
            fields: [
                { name: 'tagline', type: 'text', label: 'Tagline', placeholder: 'DIGITAL GROWTH AGENCY' },
                { name: 'headlineLine1', type: 'text', label: 'Headline - Line 1', placeholder: 'Stop Chasing Leads' },
                { name: 'headlineLine2', type: 'text', label: 'Headline - Line 2', placeholder: 'Online' },
                { name: 'description', type: 'text', label: 'Description' },
                { name: 'primaryButtonText', type: 'text', label: 'Primary Button Text', placeholder: 'Audit My Presence' },
                { name: 'secondaryButtonText', type: 'text', label: 'Secondary Button Text', placeholder: 'See Results' },
                { name: 'backgroundImage', type: 'image', label: 'Background Image', specs: 'MAX 2MB • PNG, JPG, WEBP' },
            ],
        },
        {
            id: 'trustMetrics',
            title: 'Trust Metrics',
            icon: 'chart',
            fields: [
                { name: 'stat1Value', type: 'text', label: 'Stat 1 Value', placeholder: '99' },
                { name: 'stat1Label', type: 'text', label: 'Stat 1 Label', placeholder: 'AVG SPEED SCORE' },
                { name: 'stat2Value', type: 'text', label: 'Stat 2 Value', placeholder: '40%' },
                { name: 'stat2Label', type: 'text', label: 'Stat 2 Label', placeholder: 'BOUNCE RATE REDUCTION' },
                { name: 'stat3Value', type: 'text', label: 'Stat 3 Value', placeholder: '2.5X' },
                { name: 'stat3Label', type: 'text', label: 'Stat 3 Label', placeholder: 'CONVERSION UPLIFT' },
            ],
        },
        {
            id: 'servicesIntro',
            title: 'Services Introduction',
            icon: 'target',
            fields: [
                { name: 'sectionTitle', type: 'text', label: 'Section Title', placeholder: 'Revenue-First Digital Services' },
                { name: 'sectionSubtitle', type: 'text', label: 'Section Subtitle', placeholder: "Most agencies focus on 'pretty'. We focus on 'profitable'." },
                // Service 1: Web Development
                { name: 'service1Heading', type: 'text', label: 'Service 1 - Heading', placeholder: 'High-Performance Web Development' },
                { name: 'service1Description', type: 'text', label: 'Service 1 - Description', placeholder: 'We build digital experiences that load instantly and convert visitors into customers.' },
                { name: 'service1Image', type: 'image', label: 'Service 1 - Image', specs: 'MAX 2MB • PNG, JPG, WEBP' },
                // Service 2: Digital Marketing
                { name: 'service2Heading', type: 'text', label: 'Service 2 - Heading', placeholder: 'Data-Driven Digital Marketing' },
                { name: 'service2Description', type: 'text', label: 'Service 2 - Description', placeholder: 'Stop guessing. Start scaling with precision-targeted campaigns.' },
                { name: 'service2Image', type: 'image', label: 'Service 2 - Image', specs: 'MAX 2MB • PNG, JPG, WEBP' },
                // Service 3: Video Editing
                { name: 'service3Heading', type: 'text', label: 'Service 3 - Heading', placeholder: 'Visual Storytelling & Video' },
                { name: 'service3Description', type: 'text', label: 'Service 3 - Description', placeholder: 'Capture attention in the first 3 seconds with high-retention video content.' },
                { name: 'service3Image', type: 'image', label: 'Service 3 - Image', specs: 'MAX 2MB • PNG, JPG, WEBP' },
            ],
        },
        {
            id: 'whyImpact224',
            title: 'Why Impact 224 Section',
            icon: 'award',
            fields: [
                { name: 'sectionTitle', type: 'text', label: 'Section Title', placeholder: 'Why Impact 224?' },
                // Feature 1
                { name: 'feature1Title', type: 'text', label: 'Feature 1 - Title', placeholder: 'Conversion First Design' },
                { name: 'feature1Icon', type: 'text', label: 'Feature 1 - Icon Name', placeholder: 'Zap' },
                // Feature 2
                { name: 'feature2Title', type: 'text', label: 'Feature 2 - Title', placeholder: 'Data-Driven Identity' },
                { name: 'feature2Icon', type: 'text', label: 'Feature 2 - Icon Name', placeholder: 'Users' },
                // Feature 3
                { name: 'feature3Title', type: 'text', label: 'Feature 3 - Title', placeholder: '99/100 Speed Score' },
                { name: 'feature3Icon', type: 'text', label: 'Feature 3 - Icon Name', placeholder: 'TrendingUp' },
                // Feature 4
                { name: 'feature4Title', type: 'text', label: 'Feature 4 - Title', placeholder: '24/7 Priority Support' },
                { name: 'feature4Icon', type: 'text', label: 'Feature 4 - Icon Name', placeholder: 'CheckCircle2' },
            ],
        },
        {
            id: 'projectsShowcase',
            title: 'Projects Showcase Section',
            icon: 'briefcase',
            fields: [
                // Section Header
                { name: 'sectionTitle', type: 'text', label: 'Section Title', placeholder: 'Recent Success Stories' },
                { name: 'sectionSubtitle', type: 'text', label: 'Section Subtitle', placeholder: 'Real businesses. Real growth. Real numbers.' },
                { name: 'buttonText', type: 'text', label: 'Button Text', placeholder: 'View All Case Studies' },
                // Project 1
                { name: 'project1Title', type: 'text', label: 'Project 1 - Title', placeholder: 'FinTech Global Dashboard' },
                { name: 'project1Stats', type: 'text', label: 'Project 1 - Stats', placeholder: '40% INCREASE IN RETENTION' },
                { name: 'project1Image', type: 'image', label: 'Project 1 - Image', specs: 'MAX 2MB • PNG, JPG, WEBP' },
                // Project 2
                { name: 'project2Title', type: 'text', label: 'Project 2 - Title', placeholder: 'Nike Summer Campaign' },
                { name: 'project2Stats', type: 'text', label: 'Project 2 - Stats', placeholder: '3.5X ROAS' },
                { name: 'project2Image', type: 'image', label: 'Project 2 - Image', specs: 'MAX 2MB • PNG, JPG, WEBP' },
                // Project 3
                { name: 'project3Title', type: 'text', label: 'Project 3 - Title', placeholder: 'TechTalks Docuseries' },
                { name: 'project3Stats', type: 'text', label: 'Project 3 - Stats', placeholder: '1M+ VIEWS ORGANIC' },
                { name: 'project3Image', type: 'image', label: 'Project 3 - Image', specs: 'MAX 2MB • PNG, JPG, WEBP' },
                // Project 4
                { name: 'project4Title', type: 'text', label: 'Project 4 - Title', placeholder: 'Real Estate Lead Funnel' },
                { name: 'project4Stats', type: 'text', label: 'Project 4 - Stats', placeholder: '200+ LEADS/MONTH' },
                { name: 'project4Image', type: 'image', label: 'Project 4 - Image', specs: 'MAX 2MB • PNG, JPG, WEBP' },
            ],
        },
        {
            id: 'latestInsights',
            title: 'Latest Insights Section',
            icon: 'newspaper',
            fields: [
                // Section Header
                { name: 'sectionTitle', type: 'text', label: 'Section Title', placeholder: 'Latest Insights' },
                { name: 'sectionSubtitle', type: 'text', label: 'Section Subtitle', placeholder: 'Strategies to dominate your niche.' },
                // Blog Post 1
                { name: 'blog1Category', type: 'text', label: 'Blog 1 - Category', placeholder: 'STRATEGY' },
                { name: 'blog1Image', type: 'image', label: 'Blog 1 - Image', specs: 'MAX 2MB • PNG, JPG, WEBP' },
                { name: 'blog1Title', type: 'text', label: 'Blog 1 - Title', placeholder: 'The Death of Traditional SEO: What\'s Next in 2025?' },
                { name: 'blog1Date', type: 'text', label: 'Blog 1 - Date', placeholder: 'Oct 24, 2024' },
                { name: 'blog1ReadTime', type: 'text', label: 'Blog 1 - Read Time', placeholder: '6 min read' },
                // Blog Post 2
                { name: 'blog2Category', type: 'text', label: 'Blog 2 - Category', placeholder: 'UX/UI DESIGN' },
                { name: 'blog2Image', type: 'image', label: 'Blog 2 - Image', specs: 'MAX 2MB • PNG, JPG, WEBP' },
                { name: 'blog2Title', type: 'text', label: 'Blog 2 - Title', placeholder: 'Why Your Website Conversion Rate is Low (And How to Fix It)' },
                { name: 'blog2Date', type: 'text', label: 'Blog 2 - Date', placeholder: 'Oct 20, 2024' },
                { name: 'blog2ReadTime', type: 'text', label: 'Blog 2 - Read Time', placeholder: '8 min read' },
                // Blog Post 3
                { name: 'blog3Category', type: 'text', label: 'Blog 3 - Category', placeholder: 'PAID MEDIA' },
                { name: 'blog3Image', type: 'image', label: 'Blog 3 - Image', specs: 'MAX 2MB • PNG, JPG, WEBP' },
                { name: 'blog3Title', type: 'text', label: 'Blog 3 - Title', placeholder: 'Maximizing ROAS on Meta Ads in a Post-Cookie World' },
                { name: 'blog3Date', type: 'text', label: 'Blog 3 - Date', placeholder: 'Oct 15, 2024' },
                { name: 'blog3ReadTime', type: 'text', label: 'Blog 3 - Read Time', placeholder: '5 min read' },
                // Blog Post 4
                { name: 'blog4Category', type: 'text', label: 'Blog 4 - Category', placeholder: 'BRANDING' },
                { name: 'blog4Image', type: 'image', label: 'Blog 4 - Image', specs: 'MAX 2MB • PNG, JPG, WEBP' },
                { name: 'blog4Title', type: 'text', label: 'Blog 4 - Title', placeholder: 'Brand Storytelling: The Only Moat Left' },
                { name: 'blog4Date', type: 'text', label: 'Blog 4 - Date', placeholder: 'Oct 10, 2024' },
                { name: 'blog4ReadTime', type: 'text', label: 'Blog 4 - Read Time', placeholder: '7 min read' },
            ],
        },
    ],
};

export const defaultHomeData: HomePageData = {
    hero: {
        tagline: 'DIGITAL GROWTH AGENCY',
        headlineLine1: 'Stop Chasing Leads',
        headlineLine2: 'Online',
        description: 'WE BUILD HIGH-PERFORMANCE WEBSITES AND AUTOMATED MARKETING SYSTEMS.',
        primaryButtonText: 'Audit My Presence',
        secondaryButtonText: 'See Results',
        backgroundImage: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80&w=2000',
    },
    trustMetrics: {
        stat1Value: '99',
        stat1Label: 'AVG SPEED SCORE',
        stat2Value: '40%',
        stat2Label: 'BOUNCE RATE REDUCTION',
        stat3Value: '2.5X',
        stat3Label: 'CONVERSION UPLIFT',
    },
    servicesIntro: {
        sectionTitle: 'Revenue-First Digital Services',
        sectionSubtitle: "Most agencies focus on 'pretty'. We focus on 'profitable'.",
        service1Heading: 'High-Performance Web Development',
        service1Description: 'We build digital experiences that load instantly and convert visitors into customers.',
        service1Image: 'https://images.unsplash.com/photo-1547658719-da2b51169166?auto=format&fit=crop&q=80&w=1200',
        service2Heading: 'Data-Driven Digital Marketing',
        service2Description: 'Stop guessing. Start scaling with precision-targeted campaigns.',
        service2Image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=1200',
        service3Heading: 'Visual Storytelling & Video',
        service3Description: 'Capture attention in the first 3 seconds with high-retention video content.',
        service3Image: 'https://images.unsplash.com/photo-1579632652768-6cb9dcf85912?auto=format&fit=crop&q=80&w=1200',
    },
    whyImpact224: {
        sectionTitle: 'Why Impact 224?',
        feature1Title: 'Conversion First Design',
        feature1Icon: 'Zap',
        feature2Title: 'Data-Driven Identity',
        feature2Icon: 'Users',
        feature3Title: '99/100 Speed Score',
        feature3Icon: 'TrendingUp',
        feature4Title: '24/7 Priority Support',
        feature4Icon: 'CheckCircle2',
    },
    projectsShowcase: {
        sectionTitle: 'Recent Success Stories',
        sectionSubtitle: 'Real businesses. Real growth. Real numbers.',
        buttonText: 'View All Case Studies',
        project1Title: 'FinTech Global Dashboard',
        project1Stats: '40% INCREASE IN RETENTION',
        project1Image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=1200',
        project2Title: 'Nike Summer Campaign',
        project2Stats: '3.5X ROAS',
        project2Image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&q=80&w=1200',
        project3Title: 'TechTalks Docuseries',
        project3Stats: '1M+ VIEWS ORGANIC',
        project3Image: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&q=80&w=1200',
        project4Title: 'Real Estate Lead Funnel',
        project4Stats: '200+ LEADS/MONTH',
        project4Image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&q=80&w=1200',
    },
    latestInsights: {
        sectionTitle: 'Latest Insights',
        sectionSubtitle: 'Strategies to dominate your niche.',
        blog1Category: 'Strategy',
        blog1Image: 'https://images.unsplash.com/photo-1571786256017-aee7a0c009b6?auto=format&fit=crop&q=80&w=1200',
        blog1Title: 'The Death of Traditional SEO: What\'s Next in 2025?',
        blog1Date: 'Oct 24, 2024',
        blog1ReadTime: '6 min read',
        blog2Category: 'UX/UI Design',
        blog2Image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=1200',
        blog2Title: 'Why Your Website Conversion Rate is Low (And How to Fix It)',
        blog2Date: 'Oct 20, 2024',
        blog2ReadTime: '8 min read',
        blog3Category: 'Paid Media',
        blog3Image: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?auto=format&fit=crop&q=80&w=1200',
        blog3Title: 'Maximizing ROAS on Meta Ads in a Post-Cookie World',
        blog3Date: 'Oct 15, 2024',
        blog3ReadTime: '5 min read',
        blog4Category: 'Branding',
        blog4Image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&q=80&w=1200',
        blog4Title: 'Brand Storytelling: The Only Moat Left',
        blog4Date: 'Oct 10, 2024',
        blog4ReadTime: '7 min read',
    },
};
